spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration?useSSL=false&serverTimezone=UTC
    username: root
    password: dupa123
  jpa:
    hibernate:
      dll: create-drop
    show-sql: true
