server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: dupa123
    url: jdbc:mysql://localhost:3306/registration?useSSL=false&serverTimezone=UTC
    username: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
